// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PhotoGallery.Models;
using System;

namespace PhotoGallery.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180214210129_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("PhotoGallery.Models.Gallery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CoverImage_Id");

                    b.Property<DateTime>("CreateDateTime");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("CoverImage_Id");

                    b.ToTable("Galleries");
                });

            modelBuilder.Entity("PhotoGallery.Models.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("Gallery_Id");

                    b.Property<bool>("IsCarouselImage");

                    b.Property<string>("PathName");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("Gallery_Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("PhotoGallery.Models.Gallery", b =>
                {
                    b.HasOne("PhotoGallery.Models.Image", "CoverImage")
                        .WithMany()
                        .HasForeignKey("CoverImage_Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PhotoGallery.Models.Image", b =>
                {
                    b.HasOne("PhotoGallery.Models.Gallery", "Gallery")
                        .WithMany()
                        .HasForeignKey("Gallery_Id");
                });
#pragma warning restore 612, 618
        }
    }
}
